### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by mattshoaf** [kalabox/kalabox-app-pantheon#122]
I need to allow PUT commands to come through the Drupal Services module, but am met with a 405 error. Thinking that I could add:

```
location / {
      root /code;
      client_body_temp_path /files/client_temp;
      dav_methods PUT;
} 
```

as the nginx docs recommend to the drupal.conf file would work, but I get a 502 error after restarting kbox no matter where I add that setting (drupal/backgrop/nginx.conf).
I have a ticket open with Pantheon to see what I need to do on the cloud side, but would like to get this working for local development as well.

Thanks

**Comment by pirog** [comment]
I don't think that we can currently support this on Kalabox at this time although in the future we'd like to.

That said what OS are you using? I can provide some pointers to help you troubleshoot your customizations.

**Comment by mattshoaf** [comment]
I'm on a Mac. I have a ticket open on the Pantheon cloud side, and they're saying that they don't use the nginx http_dav as I had originally interpreted so I'm going to close this until I figure out what's going on.
Thanks.

**Comment by pirog** [comment]
OK good to know. We definitely try to mock what they do as close as possible so if they dont support it then neither should kalabox, at least for the pantheon apps. 

For the stock drupal app you can obviously do what you want. :)
