### ISSUE TITLE
no such identity: /config/.ssh/pantheon.kalabox.id_rsa: Permission denied

### ISSUE THREAD

**Issue by pancho2jr** [kalabox/kalabox-app-pantheon#128]
I have problems while trying kbox pull , and kbox push. 
in the terminal it tells me to put my password from pantheon and then it works , this happend two times while pulling the data base , and while pulling files...

**Comment by pirog** [comment]
@pancho2jr what OS are you using? and what version of Kalabox?

Can you tell me what you have inside of `~/.ssh`? It seems like your SSH keys are not being created correctly.

**Comment by pancho2jr** [comment]
I am using Ubuntu 14.04 LTS  , kalabox v.0.12.0-alpha.19
inside my .ssh : 
id_rsa id_rsa.pub 
known_host 
pantheon.kalabox.id_rsa 
pantheon.kalabox.id_rsa.pub
I uninstall kalabox , then reinstall but nothing the only thing that helps is to change permissions to my project . and then kalabox ask me for my pantheon password.

no such identity: /config/.ssh/pantheon.kalabox.id_rsa: Permission denied
codeserver.dev.931c5f25-de96-4@codeserver.dev.931c5f25-de96-4350-98fd-b99a5267dc4e.drush.in's password: 

after i enter my pantheon password it pull correctly the db and files , well this password checks happend when pulling db , and when pulling files..

**Comment by pirog** [comment]
We test pretty thoroughly on 14.04. The most likely explanation here is you
have weird permissions set on either your .ssh directory or the pantheon
Kalabox keys theme selves.

Can you detail what you are doing when you change permissions on a project?
Specifically are the permissions before and after you change them.

Also can you post the permissions of your .ssh directory and the files it
contains?

**Comment by pancho2jr** [comment]
Hi sorry for the delay.
Ok here is what happens when trying to create a new project.

Creating.
Cleaning up.
Creating app structure.
Downloading: [NaN%] ...ox-app-pantheon/tarball/v0.12.0-alpha.10
Downloading: [NaN%] ...ox-app-pantheon/tarball/v0.12.0-alpha.10
Configuring app.
Running pre create tasks.
Starting app.
Starting.
Cleaning up.
Running pre start tasks.
Sharing code.
Starting containers.
Starting latinoschools_redis_1
Creating latinoschools_data_1
Recreating latinoschools_solr_1
Pulling solr (kalabox/pantheon-solr:v0.12.0-alpha.10)...
Pulling image kalabox/pantheon-solr.
Creating latinoschools_db_1
Pulling appserver (kalabox/pantheon-appserver:v0.12.0-alpha.10)...
Pulling image kalabox/pantheon-appserver.
Creating latinoschools_appserver_1
Pulling edge (kalabox/pantheon-edge:v0.12.0-alpha.10)...
Pulling image kalabox/pantheon-edge.
Creating latinoschools_edge_1
Creating latinoschools_cli_1
Pulling terminus (kalabox/terminus:v0.12.0-alpha.10)...
Pulling image kalabox/terminus.
Creating latinoschools_terminus_1
Running post start tasks.
Running post create tasks.
Pulling screenshot.
Downloading: [8.8%] ...5f25-de96-4350-98fd-b99a5267dc4e_dev.png
Pulling code.
Cloning into '.'...
/code/.git: Permission denied
Pulling database.
Warning: Permanently added '[appserver.dev.931c5f25-de96-4350-98fd-b99a5267dc4e.drush.in]:2222,[162.209.95.5]:2222' (RSA) to the list of known hosts.
mysql --user=pantheon --password=e1ab5aba4b1e42ecb9e01ecb769981f6 --database=pantheon --host=dbserver.dev.931c5f25-de96-4350-98fd-b99a5267dc4e.drush.in --port=22997
Pulling files.
files_dev/ABOUT US_Our campuses_Ecuador.jpg
files_dev/IMG_5618.JPG
files_dev/P1020649A_4.jpg
files_dev/11112460_10200644881360943_171419631429303859_n_0.jpg
files_dev/Living_Student-residence-1.jpg
files_dev/20150619_131751(0).jpg
files_dev/Contact-us-4.jpg
files_dev/P1020649A_0.jpg
files_dev/MAQUETA HOME3-02.png
files_dev/20150618_140551.jpg
files_dev/Living_Student-residence-2.jpg
files_dev/Academic-programs_Intensive-programs-2.jpg
files_dev/About-us_Campuses_Peru-2_0.jpg
files_dev/Contact-us-3.jpg
files_dev/About-us_Campuses_Ecuador-3.jpg
files_dev/11147071_368822879993105_2810076792872740100_n.jpg
files_dev/P1020649A_1.jpg
files_dev/IMG_6168.JPG
files_dev/2016-04-05.png
files_dev/47b7d600b3127cceb99cf354056400000026100QcOW7Jqzbsb.jpg
files_dev/Contact-us-1.jpg
files_dev/LIVING_Homestay_0.jpg
files_dev/DSC03692.JPG
files_dev/IMG_6178.JPG
files_dev/Embajada_Canada2.jpg
files_dev/About-us_Campuses_Ecuador-2.jpg
files_dev/Academic-programs_Humanity-courses-2.jpg
files_dev/IMG_6610.JPG
files_dev/Contact-us-1_0.jpg
files_dev/P1020649A_3.jpg
files_dev/IMG_5651.JPG
files_dev/.htaccess
files_dev/About-us_Campuses_Bolivia-2.jpg
files_dev/DSC03438.JPG
files_dev/IMG_6245.JPG
files_dev/CloudForest2.JPG
files_dev/IMG_6174_0.JPG
files_dev/IMG_8602.JPG
files_dev/Academic-programs_Intensive-programs-1.jpg
files_dev/About-us_Campuses_Peru-3.jpg
files_dev/IMG_6096.JPG
files_dev/GRANADERO_DE_TARQUI.JPG
files_dev/Noticia-3.jpg
files_dev/Academic-programs_Humanity-courses-3.jpg
files_dev/NMSU_seal.png
files_dev/CIMG0191.JPG
files_dev/Living_Homestay-1.jpg
files_dev/Academic-programs_University-credits-2.jpg
files_dev/HDR2_Columbia-River-High-Sc.jpg
files_dev/10409220_1125769047439590_582040787891453913_n.jpg
files_dev/P1100744.JPG
files_dev/IMG_1182.jpg
files_dev/-40755670541974FC6.png
files_dev/About-us_Who-we-are-3.jpg
files_dev/.gitignore
files_dev/About-us_Campuses_Bolivia-3.jpg
files_dev/10407955_1135100976516653_4299546021170545700_n_0.jpg
files_dev/Academic-programs_Humanity-courses-1.jpg
files_dev/Living_Homestay-3.jpg
files_dev/DSC00043.JPG
files_dev/About-us_Our-partners-1.jpg
files_dev/APPLICATION-FORM-MAPA_03.png
files_dev/IMG_1176.jpg
files_dev/About-us_Who-we-are-2.jpg
files_dev/Living_Student-residence-3.jpg
files_dev/20150619_131751(0)_2.jpg
files_dev/About-us_Campuses_Peru-1.jpg
files_dev/P1020649A_2.jpg
files_dev/Living_Homestay-2.jpg
files_dev/LatinoSchools ICONO1.jpg
files_dev/Ecuador Galapagos-242.jpg
files_dev/DSC01344.JPG
files_dev/11112460_10200644881360943_171419631429303859_n.jpg
files_dev/DSC00071.JPG
files_dev/DSC00054.JPG
files_dev/About-us_Campuses_Bolivia-1.jpg
files_dev/CIMG0154.JPG
files_dev/Koica Mark Logo.jpg
files_dev/Academic-programs_University-credits-1.jpg
files_dev/DSC03493.JPG
files_dev/Contact-us-2.jpg
files_dev/Academic-programs_Intensive-programs-3.jpg
files_dev/Ecuador.jpg
files_dev/IMG_2127.JPG
files_dev/20150619_131751(0)_1.jpg
files_dev/DSC_0398.JPG
files_dev/Academic-programs_University-credits-3.jpg
files_dev/Logo oficial para sitio web TRANS.png
files_dev/P1020649A.jpg
files_dev/IMG_5987.JPG
files_dev/About-us_Campuses_Bolivia-3_0.jpg
files_dev/About-us_Who-we-are-1.jpg
files_dev/Department_of_state_logo.png
files_dev/IMG_6366.JPG
files_dev/Academia estudiantes Quito.jpg
files_dev/About-us_Campuses_Ecuador-1.jpg
files_dev/IMG_6640.JPG
files_dev/IMG_6501.JPG
files_dev/11224583_369478839927509_8397322684573161987_n.jpg
files_dev/IMG_6436.JPG
files_dev/CIMG0019.JPG
files_dev/our-partners.jpeg
files_dev/bandera-Peru.png
files_dev/fondo-para-OUR-PARTNERS.jpg
files_dev/oneonta.gif
files_dev/mvc-logo2.jpg
files_dev/internships-1.jpg
files_dev/cruz roja.jpg
files_dev/Volunteer-programas--2_0.jpg
files_dev/chicsa en sacsa2.png
files_dev/boliviacampus.jpg
files_dev/intern8.jpg
files_dev/Slogan 2015 B TRANS(1).png
files_dev/SANDRA Y PATY en administracion.jpg
files_dev/indigena en titicaca2.png
files_dev/fondo de corcho.jpg
files_dev/missouri.png
files_dev/alma.png
files_dev/internships-2.jpg
files_dev/Volunteer-programas--3.jpg
files_dev/estudiante con culebra.jpg
files_dev/skipped.log
files_dev/quito_0.jpg
files_dev/video_embed_field_thumbnails/youtube/_ufJ6iNcqno.jpg
files_dev/a2 (2)_0.JPG
files_dev/Slogan completo TRANS.png
files_dev/media-icons/default/file-unknown.png
files_dev/boton information lateral.png
files_dev/calle Bolivar recortada.jpg
files_dev/media-icons/default/application-octet-stream.png
files_dev/ekquator 028.JPG
files_dev/a2 (2).JPG
files_dev/media-icons/default/video-x-generic.png
files_dev/chicas con diablumas.jpg
files_dev/is660056.jpg
files_dev/calle bolivar recortada2.png
files_dev/SUNY_Geneseo_seal.png
files_dev/chica-con-piqueros.jpg
files_dev/RIMG9823.JPG
files_dev/quito_1.jpg
files_dev/SANDRA Y PATY en administracion (1).jpg
files_dev/homestaybanner.png
files_dev/video_embed_field_thumbnails/youtube/_bfkykIVu7c.jpg
files_dev/perucampus.jpg
files_dev/bandera-Ecuador.png
files_dev/fullColorLogo.jpg
files_dev/pilar bahamonde.jpg
files_dev/img_como_funciona_el_banco_mundial_26031_300.jpg
files_dev/boton informacion.png
files_dev/Slogan 2015 B TRANS.png
files_dev/chica-con-bici.jpg
files_dev/media-icons/default/image-x-generic.png
files_dev/mapa sucre antiguo 009.jpg
files_dev/chico-en-macchu-picchu_0.jpg
files_dev/video_embed_field_thumbnails/youtube/xjswRsab9PI.jpg
files_dev/bulldoglogo.png
files_dev/claudia-y-estudiante.jpg
files_dev/UNM.jpg
files_dev/chico-en-macchu-picchu.jpg
files_dev/chica en pto lopez 3.jpg
files_dev/chica en sacsa.jpg
files_dev/Prices-1.jpg
files_dev/our-campuses.jpg
files_dev/logo.png
files_dev/intern8_0.jpg
files_dev/logo_03.png
files_dev/who-we-are.jpg
files_dev/varios 003.jpg
files_dev/Volunteer-programas--1.jpg
files_dev/huellas3.JPG
files_dev/ecuador.jpg
files_dev/media-icons/default/audio-mpeg.png
files_dev/internships-3.jpg
files_dev/chicas con diablumas_0.jpg
files_dev/media-icons/default/audio-x-generic.png
files_dev/video_embed_field_thumbnails/youtube/aCwLjXH0f-Y.jpg
files_dev/a2 (2)_1.JPG
files_dev/cocina-peruana(1).jpg
files_dev/.htaccess
files_dev/skipped.log
mv: can't create '/media/-40755670541974FC6.png': Permission denied
mv: can't create '/media/10407955_1135100976516653_4299546021170545700_n_0.jpg': Permission denied
mv: can't create '/media/10409220_1125769047439590_582040787891453913_n.jpg': Permission denied
mv: can't create '/media/11112460_10200644881360943_171419631429303859_n.jpg': Permission denied
mv: can't create '/media/11112460_10200644881360943_171419631429303859_n_0.jpg': Permission denied
mv: can't create '/media/11147071_368822879993105_2810076792872740100_n.jpg': Permission denied
mv: can't create '/media/11224583_369478839927509_8397322684573161987_n.jpg': Permission denied
mv: can't create '/media/20150618_140551.jpg': Permission denied
mv: can't create '/media/20150619_131751(0).jpg': Permission denied
mv: can't create '/media/20150619_131751(0)_1.jpg': Permission denied
mv: can't create '/media/20150619_131751(0)_2.jpg': Permission denied
mv: can't create '/media/2016-04-05.png': Permission denied
mv: can't create '/media/47b7d600b3127cceb99cf354056400000026100QcOW7Jqzbsb.jpg': Permission denied
mv: can't create '/media/ABOUT US_Our campuses_Ecuador.jpg': Permission denied
mv: can't create '/media/APPLICATION-FORM-MAPA_03.png': Permission denied
mv: can't create '/media/About-us_Campuses_Bolivia-1.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Bolivia-2.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Bolivia-3.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Bolivia-3_0.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Ecuador-1.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Ecuador-2.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Ecuador-3.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Peru-1.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Peru-2_0.jpg': Permission denied
mv: can't create '/media/About-us_Campuses_Peru-3.jpg': Permission denied
mv: can't create '/media/About-us_Our-partners-1.jpg': Permission denied
mv: can't create '/media/About-us_Who-we-are-1.jpg': Permission denied
mv: can't create '/media/About-us_Who-we-are-2.jpg': Permission denied
mv: can't create '/media/About-us_Who-we-are-3.jpg': Permission denied
mv: can't create '/media/Academia estudiantes Quito.jpg': Permission denied
mv: can't create '/media/Academic-programs_Humanity-courses-1.jpg': Permission denied
mv: can't create '/media/Academic-programs_Humanity-courses-2.jpg': Permission denied
mv: can't create '/media/Academic-programs_Humanity-courses-3.jpg': Permission denied
mv: can't create '/media/Academic-programs_Intensive-programs-1.jpg': Permission denied
mv: can't create '/media/Academic-programs_Intensive-programs-2.jpg': Permission denied
mv: can't create '/media/Academic-programs_Intensive-programs-3.jpg': Permission denied
mv: can't create '/media/Academic-programs_University-credits-1.jpg': Permission denied
mv: can't create '/media/Academic-programs_University-credits-2.jpg': Permission denied
mv: can't create '/media/Academic-programs_University-credits-3.jpg': Permission denied
mv: can't create '/media/CIMG0019.JPG': Permission denied
mv: can't create '/media/CIMG0154.JPG': Permission denied
mv: can't create '/media/CIMG0191.JPG': Permission denied
mv: can't create '/media/CloudForest2.JPG': Permission denied
mv: can't create '/media/Contact-us-1.jpg': Permission denied
mv: can't create '/media/Contact-us-1_0.jpg': Permission denied
mv: can't create '/media/Contact-us-2.jpg': Permission denied
mv: can't create '/media/Contact-us-3.jpg': Permission denied
mv: can't create '/media/Contact-us-4.jpg': Permission denied
mv: can't create '/media/DSC00043.JPG': Permission denied
mv: can't create '/media/DSC00054.JPG': Permission denied
mv: can't create '/media/DSC00071.JPG': Permission denied
mv: can't create '/media/DSC01344.JPG': Permission denied
mv: can't create '/media/DSC03438.JPG': Permission denied
mv: can't create '/media/DSC03493.JPG': Permission denied
mv: can't create '/media/DSC03692.JPG': Permission denied
mv: can't create '/media/DSC_0398.JPG': Permission denied
mv: can't create '/media/Department_of_state_logo.png': Permission denied
mv: can't create '/media/Ecuador Galapagos-242.jpg': Permission denied
mv: can't create '/media/Ecuador.jpg': Permission denied
mv: can't create '/media/Embajada_Canada2.jpg': Permission denied
mv: can't create '/media/GRANADERO_DE_TARQUI.JPG': Permission denied
mv: can't create '/media/HDR2_Columbia-River-High-Sc.jpg': Permission denied
mv: can't create '/media/IMG_1176.jpg': Permission denied
mv: can't create '/media/IMG_1182.jpg': Permission denied
mv: can't create '/media/IMG_2127.JPG': Permission denied
mv: can't create '/media/IMG_5618.JPG': Permission denied
mv: can't create '/media/IMG_5651.JPG': Permission denied
mv: can't create '/media/IMG_5987.JPG': Permission denied
mv: can't create '/media/IMG_6096.JPG': Permission denied
mv: can't create '/media/IMG_6168.JPG': Permission denied
mv: can't create '/media/IMG_6174_0.JPG': Permission denied
mv: can't create '/media/IMG_6178.JPG': Permission denied
mv: can't create '/media/IMG_6245.JPG': Permission denied
mv: can't create '/media/IMG_6366.JPG': Permission denied
mv: can't create '/media/IMG_6436.JPG': Permission denied
mv: can't create '/media/IMG_6501.JPG': Permission denied
mv: can't create '/media/IMG_6610.JPG': Permission denied
mv: can't create '/media/IMG_6640.JPG': Permission denied
mv: can't create '/media/IMG_8602.JPG': Permission denied
mv: can't create '/media/Koica Mark Logo.jpg': Permission denied
mv: can't create '/media/LIVING_Homestay_0.jpg': Permission denied
mv: can't create '/media/LatinoSchools ICONO1.jpg': Permission denied
mv: can't create '/media/Living_Homestay-1.jpg': Permission denied
mv: can't create '/media/Living_Homestay-2.jpg': Permission denied
mv: can't create '/media/Living_Homestay-3.jpg': Permission denied
mv: can't create '/media/Living_Student-residence-1.jpg': Permission denied
mv: can't create '/media/Living_Student-residence-2.jpg': Permission denied
mv: can't create '/media/Living_Student-residence-3.jpg': Permission denied
mv: can't create '/media/Logo oficial para sitio web TRANS.png': Permission denied
mv: can't create '/media/MAQUETA HOME3-02.png': Permission denied
mv: can't create '/media/NMSU_seal.png': Permission denied
mv: can't create '/media/Noticia-3.jpg': Permission denied
mv: can't create '/media/P1020649A.jpg': Permission denied
mv: can't create '/media/P1020649A_0.jpg': Permission denied
mv: can't create '/media/P1020649A_1.jpg': Permission denied
mv: can't create '/media/P1020649A_2.jpg': Permission denied
mv: can't create '/media/P1020649A_3.jpg': Permission denied
mv: can't create '/media/P1020649A_4.jpg': Permission denied
mv: can't create '/media/P1100744.JPG': Permission denied
mv: can't create '/media/Prices-1.jpg': Permission denied
mv: can't create '/media/RIMG9823.JPG': Permission denied
mv: can't create '/media/SANDRA Y PATY en administracion (1).jpg': Permission denied
mv: can't create '/media/SANDRA Y PATY en administracion.jpg': Permission denied
mv: can't create '/media/SUNY_Geneseo_seal.png': Permission denied
mv: can't create '/media/Slogan 2015 B TRANS(1).png': Permission denied
mv: can't create '/media/Slogan 2015 B TRANS.png': Permission denied
mv: can't create '/media/Slogan completo TRANS.png': Permission denied
mv: can't create '/media/UNM.jpg': Permission denied
mv: can't create '/media/Volunteer-programas--1.jpg': Permission denied
mv: can't create '/media/Volunteer-programas--2_0.jpg': Permission denied
mv: can't create '/media/Volunteer-programas--3.jpg': Permission denied
mv: can't create '/media/a2 (2).JPG': Permission denied
mv: can't create '/media/a2 (2)_0.JPG': Permission denied
mv: can't create '/media/a2 (2)_1.JPG': Permission denied
mv: can't create '/media/alma.png': Permission denied
mv: can't create '/media/bandera-Ecuador.png': Permission denied
mv: can't create '/media/bandera-Peru.png': Permission denied
mv: can't create '/media/boliviacampus.jpg': Permission denied
mv: can't create '/media/boton informacion.png': Permission denied
mv: can't create '/media/boton information lateral.png': Permission denied
mv: can't create '/media/bulldoglogo.png': Permission denied
mv: can't create '/media/calle Bolivar recortada.jpg': Permission denied
mv: can't create '/media/calle bolivar recortada2.png': Permission denied
mv: can't create '/media/chica en pto lopez 3.jpg': Permission denied
mv: can't create '/media/chica en sacsa.jpg': Permission denied
mv: can't create '/media/chica-con-bici.jpg': Permission denied
mv: can't create '/media/chica-con-piqueros.jpg': Permission denied
mv: can't create '/media/chicas con diablumas.jpg': Permission denied
mv: can't create '/media/chicas con diablumas_0.jpg': Permission denied
mv: can't create '/media/chico-en-macchu-picchu.jpg': Permission denied
mv: can't create '/media/chico-en-macchu-picchu_0.jpg': Permission denied
mv: can't create '/media/chicsa en sacsa2.png': Permission denied
mv: can't create '/media/claudia-y-estudiante.jpg': Permission denied
mv: can't create '/media/cocina-peruana(1).jpg': Permission denied
mv: can't create '/media/cruz roja.jpg': Permission denied
mv: can't create '/media/ecuador.jpg': Permission denied
mv: can't create '/media/ekquator 028.JPG': Permission denied
mv: can't create '/media/estudiante con culebra.jpg': Permission denied
mv: can't create '/media/fondo de corcho.jpg': Permission denied
mv: can't create '/media/fondo-para-OUR-PARTNERS.jpg': Permission denied
mv: can't create '/media/fullColorLogo.jpg': Permission denied
mv: can't create '/media/homestaybanner.png': Permission denied
mv: can't create '/media/huellas3.JPG': Permission denied
mv: can't create '/media/img_como_funciona_el_banco_mundial_26031_300.jpg': Permission denied
mv: can't create '/media/indigena en titicaca2.png': Permission denied
mv: can't create '/media/intern8.jpg': Permission denied
mv: can't create '/media/intern8_0.jpg': Permission denied
mv: can't create '/media/internships-1.jpg': Permission denied
mv: can't create '/media/internships-2.jpg': Permission denied
mv: can't create '/media/internships-3.jpg': Permission denied
mv: can't create '/media/is660056.jpg': Permission denied
mv: can't create '/media/logo.png': Permission denied
mv: can't create '/media/logo_03.png': Permission denied
mv: can't create '/media/mapa sucre antiguo 009.jpg': Permission denied
mv: can't create directory '/media/media-icons': Permission denied
mv: can't create '/media/missouri.png': Permission denied
mv: can't create '/media/mvc-logo2.jpg': Permission denied
mv: can't create '/media/oneonta.gif': Permission denied
mv: can't create '/media/our-campuses.jpg': Permission denied
mv: can't create '/media/our-partners.jpeg': Permission denied
mv: can't create '/media/perucampus.jpg': Permission denied
mv: can't create '/media/pilar bahamonde.jpg': Permission denied
mv: can't create '/media/quito_0.jpg': Permission denied
mv: can't create '/media/quito_1.jpg': Permission denied
mv: can't create '/media/skipped.log': Permission denied
mv: can't create '/media/varios 003.jpg': Permission denied
mv: can't create directory '/media/video_embed_field_thumbnails': Permission denied
mv: can't create '/media/who-we-are.jpg': Permission denied
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:140:15)
    at ReadStream.Stream.pipe (stream.js:96:10)
    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/docker.js.jx:334:25
    at tryCatcher (/usr/local/bin/node_modules/bluebird/js/main/util.js.jx:25:23)
    at Promise._settlePromiseFromHandler (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:506:31)
    at Promise._settlePromiseAt (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:580:18)
    at Promise._settlePromises (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:696:14)
    at Async._drainQueue (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:122:16)
    at Async._drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:132:10)
    at Async.drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:14:14)
    at process._tickCallback (node.js:917:13)
adduser: The GID 1002 does not exist.

My .ssh permissions:

    drwx------  2 panchodomo panchodomo  4096 abr  1 11:57 .ssh

inside my .ssh:

    -rw------- 1 panchodomo panchodomo 1675 feb 11 10:52 id_rsa
    -rw-r--r-- 1 panchodomo panchodomo  392 feb 11 10:52 id_rsa.pub
    -rw-r--r-- 1 panchodomo panchodomo 3096 abr  8 10:55 known_hosts
    -rw------- 1 panchodomo panchodomo 1675 feb 11 10:52 pantheon.kalabox.id_rsa
    -rw-r--r-- 1 panchodomo panchodomo  392 feb 11 10:52 pantheon.kalabox.id_rsa.pub

Now i am using 0.12.0-alpha.22 that seems to be the alpha 3.

My temporary fix , I think is bad to do this but .. 
chmod 777 -R "my-project-name"
after doing this while pulling kbox ask me for my pantheon password for files and for db.

**Comment by pirog** [comment]
Ok, I think i see what is happening here although im not sure why it isnt working but for whatever reason it doesnt seem to be correctly mapping your user aka 

`adduser: The GID 1002 does not exist.`

This would explain all the permission denied errors. Good news is that i think i have enough from this to try and replicate.

**Comment by pirog** [comment]
Closing in favor of https://github.com/kalabox/kalabox/issues/1253

**Comment by pancho2jr** [comment]
@pirog my boss actually help me with this problem , we found that if your SO have more than one user  then this error happens, we change the GID from the first user created to my user and then it starts working.
My UID and GID are 1000 , with this conf everything works, hope this help someone.

**Comment by pirog** [comment]
@pancho2jr that makes sense. right now kalabox is only designed with a single user in mind. I think there are a few open/closed issues that discuss this. #1253 comes to mind.
