### ISSUE TITLE
Local Environment Variables for Drupal

### ISSUE THREAD

**Issue by rjbain** [kalabox/kalabox-app-pantheon#69]
Hey guys, 

It looks like setting local variables in settings.php doesn't work in kalabox 2 :

`if (isset($_SERVER['KALABOX']) &&  $_SERVER['KALABOX'] === 'on') {}`

How is this handled now? In a Dockerfile with drush commands? 

Thanks!

**Comment by pirog** [comment]
@rjbain so you should be able to do PANTHEON_ENVIRONMENT === 'kalabox' now for that sort of thing

**Comment by pirog** [comment]
on V2 you also do not need to handle local DB settings, we take care of that for you now

**Comment by pirog** [comment]
so something like this would work in settings.php

```php
if (PANTHEON_ENVIRONMENT === 'kalabox') {
  // My kalabox specific code
}
```
also note that we just released alpha6!

**Comment by medinasod** [comment]
Thanks, @pirog! Liking what I see from kbox2 so far!

**Comment by pirog** [comment]
@rjbain @medinasod great! 

we're getting there!
