### ISSUE TITLE
Kalabox 2 not downloading images from Pantheon

### ISSUE THREAD

**Issue by rjbain** [kalabox/kalabox-app-pantheon#72]
Hey guys,

When I pull my site down from Pantheon none of the images in /sites/default/files are coming down.

I'm seeing these messages in the kbox terminal when doing a pull:

`rsync: send_files failed to open` `"/srv/bindings/5a1197836aa44e4c975ba0ef9d2665d0/files/management/usf_som-ethnicdiversity.png": Transport endpoint is not connected (107)`
`rsync: send_files failed to open` `"/srv/bindings/5a1197836aa44e4c975ba0ef9d2665d0/files/management/usf_som-founded.png":` `Transport endpoint is not connected (107)`
`rsync: send_files failed to open`  `"/srv/bindings/5a1197836aa44e4c975ba0ef9d2665d0/files/management/zhang_jing-som-ad.jpg":` `Transport endpoint is not connected (107)`
`      133573 100%  115.85kB/s    0:00:01 (xfer#633, to-check=1702/8594)`
`journals/banner/`

`sent 45117 bytes  received 321285214 bytes  993293.14 bytes/sec`
`total size is 3484792044  speedup is 10.84`
`rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1536)`  `[generator=3.0.9]`

Any Ideas?

Thanks,
Rob

**Comment by pirog** [comment]
@rjbain what is the exact command you are running? and more specifically what options are you choosing? does this happen on all your sites or just this one?

**Comment by rjbain** [comment]
@pirog it's just happening for one of my sites, and it has a lot of really heavy images on it. It seems to start pulling them fine for a while, then errors out (maybe a timeout of some kind?). 

Here's the command:

`kbox pull`

At the prompt I choose not to pull a db, just files.

Thanks!

**Comment by pirog** [comment]
@rjbain what are talking about specifically when we say "a lot of really heavy images on it"? How many and how big total? How different are those things from other sites you've pulled? Does it always fail at the same point or does it actually grab more files each successive try?

**Comment by rjbain** [comment]
@pirog The backup of files for the site is 4.1GB. The second largest site I have is half that. It doesn't seem to fail at the same point every time. It just eventually fails during the image download process. When I say a lot of large files I mean, for example:

info: DOCKER =>  status=Downloading, current=33012732, total=49793979, progress=[=================================>                 ] 33.01 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=33520636, total=49793979, progress=[=================================>                 ] 33.52 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=34028540, total=49793979, progress=[==================================>                ] 34.03 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=34536444, total=49793979, progress=[==================================>                ] 34.54 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=35044348, total=49793979, progress=[===================================>               ] 35.04 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=35552252, total=49793979, progress=[===================================>               ] 35.55 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=36060156, total=49793979, progress=[====================================>              ] 36.06 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=36568060, total=49793979, progress=[====================================>              ] 36.57 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=37075964, total=49793979, progress=[=====================================>             ] 37.08 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=37583868, total=49793979, progress=[=====================================>             ] 37.58 MB/49.79 MB, id=bc8bcce76b0d
info: DOCKER =>  status=Downloading, current=38091772, total=49793979, progress=[======================================>            ] 38.09 MB/49.79 MB, id=bc8bcce76b0d

**Comment by pirog** [comment]
So what you printed here is actually the pulling down of the containers that run your site. Is that what is crapping out or is it rsync-ing the files?

If its the files do you think if we just constantly restarted failed rsyncs we'd eventually be able to grab them all?

**Comment by rjbain** [comment]
My bad:
```
some_file.jpg
      339805 100%    1.07MB/s    0:00:00 (xfer#545, to-check=2442/5272)
some_file.jpg
      266138 100%  458.38kB/s    0:00:00 (xfer#546, to-check=2441/5272)
some_file.pdf
      208953 100%  303.65kB/s    0:00:00 (xfer#547, to-check=2440/5272)
some_file.pdf
      517761 100%  496.20kB/s    0:00:01 (xfer#548, to-check=2439/5272)
some_file.pdf
      517954 100%    1.66MB/s    0:00:00 (xfer#549, to-check=2438/5272)
rsync: send_files failed to open "/srv/bindings/5a1197836aa44e4c975ba0ef9d2665d0/files/media-youtube/gxdy0PjkN9g.jpg": Transport endpoint is not connected (107)

```
It's possible that if I just kept running it I'd get all the files... Actually I tried pulling them yesterday and it finished without errors, but then I couldn't start the app (still can't). I can start other apps I've pulled from pantheon, but not this one. 

From the kalabox/apps/[app name] directory:

`kbox start`

```
Error dispatching event listeners [post-start-component]: Error while running command "ln,-nsf,/media,/code/sites/default/files" in container 263596f23c2776168aafa4dea3c7f3441a0b543903a238278d0aff007af3f813: HTTP code is 500 which indicates error: server error - Container 263596f23c2776168aafa4dea3c7f3441a0b543903a238278d0aff007af3f813 is not running

VError: Error while running command "ln,-nsf,/media,/code/sites/default/files" in container 263596f23c2776168aafa4dea3c7f3441a0b543903a238278d0aff007af3f813: HTTP code is 500 which indicates error: server error - Container 263596f23c2776168aafa4dea3c7f3441a0b543903a238278d0aff007af3f813 is not running

```

**Comment by pirog** [comment]
Ok that's good to know because its easy to just retry rysnc until it finishes. 

I would open another ticket for this 500 issue... although i *think* there might already be one open for something like that.

**Comment by labboy0276** [comment]
I get this error from time to time since 10.5 I believe.

Easiest way to just stop banging your head against the well is to run kbox
rsync like this:

Grab the SFTP connection string from Pantheon, then copy it into the
command below

kbox rsync -rlvz --size-only --ipv4 --progress -e 'ssh -p 2222'
dev.YOURSTRINGl-lotsofcrazynumberz.drush.in:files/ sites/default/files/

And yo should be good to go

On Wed, Dec 9, 2015 at 1:54 PM, Mike Pirog <notifications@github.com> wrote:

> Ok that's good to know because its easy to just retry rysnc until it
> finishes.
>
> I would open another ticket for this 500 issue... although i *think*
> there might already be one open for something like that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-app-pantheon/issues/72#issuecomment-163356450>
> .
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by rjbain** [comment]
@labboy0276 Thanks for the tip... The downsync ran for quite a while, but it eventually errored out with the same message as above.

**Comment by pirog** [comment]
@rjbain try this on the new v0.11 and open an issue if you get a fail
