### ISSUE TITLE
Feature Request:  Let me choose whether to download my files via backup or rsync

### ISSUE THREAD

**Issue by bthompson-mindgrub** [kalabox/kalabox-app-pantheon#73]
Overview:

The `pullFiles()` function in pull.js (https://github.com/kalabox/kalabox-app-pantheon/blob/v0.10/app/plugins/kalabox-plugin-pantheon/lib/pull.js#L268) selectively determines whether or not to download files via Pantheon backup or rsync based on whether this is the initial clone of a site or not.  For most use cases, this is a great way to do it.  However, this is problematic for those sites with large files directories.

Example use case:

I have a site on Pantheon with ~40GB of files in the compressed backup (FWIW, they are largely PDFs and images).  Prior to this content being loaded into the site on Pantheon, I had cloned this site to my local machine using Kalabox.  This process worked great and continues to run great when I pull.  When I try and clone the site on a new machine (such as a new computer at work for a new team member), the initial creation takes forever and eventually errors out because Kalabox is trying to download a 40GB archive file and then decompress it.  Ultimately, this process ends up failing and leaves the local copy of the site in an unusable state (because other post-file-pull tasks haven't run).

Suggested resolution:

I see 2 different ways to resolve this.  Option 1 would be to provide a way for the user to specify that they want to download files via rsync instead of compressed archive.  This could either be a command line flag passed into the create command (seems a little wonky) or a prompt to the user when it gets to the clone step.  Option 2 (and I'm not sure if this is feasible) is to intelligently check the size of the backup in Pantheon before downloading it and if it is over a certain threshold, revert to rsync.  This option does have the negative drawback that if a backup doesn't exist and Kalabox has to make one, then the user is again stuck waiting for a long time because creating a 40GB archive of files can take hours (or more).

**Comment by pirog** [comment]
@bthompson-mindgrub do you mind recreating this issue over at kalabox/kalabox so we can track it better. 

So i think we can do both option 1 and option 2 here. that said i think the best thing you can do for large file directories is to use the drupal file proxy module. It is also worth noting that sometimes its faster to create a backup and download it vs rsyncing.

**Comment by bthompson-mindgrub** [comment]
Moved to kalabox/kalabox#851
