### ISSUE TITLE
Stylesheet caching...Varnish?

### ISSUE THREAD

**Issue by dustinleblanc** [kalabox/kalabox-app-pantheon#74]
Yo Kbox crew,

I have been having an issue with Kbox caching my stylesheets in development. I *think* it started happening when the edge container was added. I might be inferring that but it feels right. I have to clear my caches to see changes to theme files. I have double checked my performance settings and all caching is turned off. 

Is there perhaps a way to disable to varnish cache so I can test running with out it or possibly an env var I can set in my local settings file?

**Comment by rjbain** [comment]
@dustinleblanc try this in settings.php:
```
if (PANTHEON_ENVIRONMENT === 'kalabox') {
  $conf['cache'] = 0;
  $conf['css_gzip_compression'] = FALSE;
  $conf['js_gzip_compression'] = FALSE;
  $conf['preprocess_css'] = 0;
  $conf['preprocess_js'] = 0;
}
```

**Comment by labboy0276** [comment]
Hello!

There is also this issue:
https://github.com/kalabox/kalabox/issues/748

You can add to what Rob showed you and add the no cache setting.

Sometimes, in my experience, you just have to run drush cc css-js when
making theming changes when using kalabox.  Sites that use some sort of
processor are usually the culprit in this case.  Takes an extra second, but
not that big of a deal.

On Mon, Jan 4, 2016 at 6:00 PM, Rob Bain <notifications@github.com> wrote:

> @dustinleblanc <https://github.com/dustinleblanc> try this in
> settings.php:
>
> if (PANTHEON_ENVIRONMENT === 'kalabox') {
>   $conf['cache'] = 0;
>   $conf['css_gzip_compression'] = FALSE;
>   $conf['js_gzip_compression'] = FALSE;
>   $conf['preprocess_css'] = 0;
>   $conf['preprocess_js'] = 0;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-app-pantheon/issues/74#issuecomment-168838740>
> .
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by dustinleblanc** [comment]
Already setting caches off in my settings.local.

Will try the setcookie per #748

**Comment by pirog** [comment]
@dustinleblanc in v0.11 you can now bypass varnish directly by visiting appserver.appname.kbox. Check out https://github.com/kalabox/kalabox/issues/858 for some discussion on the best default settings for this.

**Comment by dustinleblanc** [comment]
Thanks! I will probably be working on a Pantheon project today so I might give this a try. I've been using drush run server for a few weeks for its blistering speed but if I have time I'll spin up the new kbox version and give that a go and see where we're at.
