### ISSUE TITLE
Suggestion: put the name of the site in the warning when running `kbox destroy`

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox-app-pantheon#76]
I suggest adding the name of the site when running kbox destroy.  This is similar to how Pantheon does it (actually, Pantheon asks you to type the site name instead of "y" to delete it, which might be too much here, since the app can be restored, but just to prevented unintended Godzilla actions it would be great to have the site name printed in the error message, maybe something like this:

     WARNING! APP  _SITENAME_ DESTRUCTION IMMINENT

  Before you continue please be aware that after you destroy
  an app there will be nothing left. That means yours app's
  codes, files, databases, indeces, caches, containers and
  EVERYTHING ELSE that has to do with your app  _SITENAME_ WILL BE GONE.

###############################################################
? So, are you still prepared to DESTROY _SITENAME_? Yes

**Comment by pirog** [comment]
@ptmkenny i think this is a good suggestion for sure. 

Can you actually add this to the kalabox/kalabox issue queue so we dont lose track of it and can add it to an upcoming sprint? Once you do that close this issue and link to teh new one

**Comment by ptmkenny** [comment]
Moved: https://github.com/kalabox/kalabox/issues/864
