### ISSUE TITLE
Accessing DB externally?

### ISSUE THREAD

**Issue by WidgetsBurritos** [kalabox/kalabox-app-pantheon#85]
So I saw for a standard Drupal install you can access the DB externally:
https://github.com/kalabox/kalabox-app-drupal#getting-to-your-database
But after that didn't work in my case, and after reading kalabox/kalabox-app-pantheon#46 and seeing that Pantheon is based on PressFlow, it seems there isn't a direct port into the database.

I've been a little bit stumped on how I might access that database from outside of my VM. 

I did a print_r() on the $pressflow_settings inside includes/bootstrap.inc and got the following information: 
```
Array
(
    [databases] => Array
        (
            [default] => Array
                (
                    [default] => Array
                        (
                            [driver] => mysql
                            [prefix] => 
                            [database] => pantheon
                            [username] => pantheon
                            [password] => 
                            [host] => database
                            [port] => 3306
                        )

                )

        )
)
```

It appears the database is running on a separate host called "database". 
When I ping "database" from inside the docker machine it shows me an IP address of 198.105.244.228. 

So I'm assuming there's a way to connect from my host machine to this internal IP address, but I don't quite know the best way of doing that. Does it involve port mapping in VirtualBox, or something separate in docker?  

I had attempted the following settings in VirtualBox, but that didn't seem to work:
![image](https://cloud.githubusercontent.com/assets/5263371/12656849/14c4c9e4-c5c6-11e5-952b-98a79728be7b.png)

I must admit, I don't use VMs very often so I'm not entirely sure the best way of dealing with the network settings. 

I tried the Bridged Adapter as well, but still couldn't access that internal IP address.   Any pointers would be helpful. 

Thanks.

**Comment by pirog** [comment]
Hey @WidgetsBurritos we've got an issue to track this
https://github.com/kalabox/kalabox/issues/899

i'd move your comments over there

**Comment by WidgetsBurritos** [comment]
Oh sorry.  Didn't mean to open a new thread.  I had assumed it was a pantheon specific issue, so I didn't think to look in the main queue.

**Comment by pirog** [comment]
No worries!

On Thu, Jan 28, 2016 at 11:58 AM, David Stinemetze <notifications@github.com
