### ISSUE TITLE
No longer have local access to Pantheon env

### ISSUE THREAD

**Issue by qcutter** [kalabox/kalabox-app-pantheon#87]
Im not sure is this is just how things are now, but previous to the .11 build I was able to have shared access to my env's site/default files. As well as access to the DB ports. Now it all seems to be locked away in the Virtual Machine. Is this because the network setting is not NAT and not bridged? how do I get the previous functionality? It made my local development way easier. Unless Im missing something.

-- Also https not working, how to do I check out the configuration for this?

**Comment by labboy0276** [comment]
Hello

Indeed, the backend changed architecture to docker compose.  

If you check this out for the DB: https://github.com/kalabox/kalabox/issues/899  

The other issues, I will let the developers reply and you guys can go form there,

**Comment by pirog** [comment]
@qcutter i would post your ticket over at kalabox/kalabox so we can track it better.

https://github.com/kalabox/kalabox/wiki/Circle-of-Trust-Testing-Guide#2-clear-replicable-issues-are-solid-gold
